language: python
python:
- 2.7
- 3.4
notifications:
email: false

before_install:
  pip install codecov 
install:
- pip install nose
- pip install mock
- pip install coverage
script:
- python setup.py install
- nosetests --with-coverage --cover-package=segments --logging-level=INFO

after_success:
- codecov
